### ISSUE TITLE
Time/Space Complexity

### ISSUE THREAD

**Issue by di-wu** [metascore/metascore#32]
We started with some very simple data structures, for which it was easy to determine the complexity of the algorithm. At this point in time this is not the case anymore. So it is time to analyze this and see where we could improve.

Some open question on how to do this:

- `Big-O` vs `Little-o` notation? (I personally prefer Little-o, but this is more work).
- `Time` vs `Space` complexity? Should we look at both?

**Comment by jorgenbuilder** [comment]
Frankly, this part isn't my strong suit but I'm happy to collaborate on it: you'll just have to tell me where I'm being an idiot or ignore me.

I don't think space complexity is a big deal here? In an extreme case of 500,000 users * (49 leaderboards + 1 overall) * 4 denormalized data structures * (32 bits of principal  + 64 bits of score) = 1.2Gb. I'm open to the math and the assumptions here to being wrong, but it feels like we have plenty of headroom in one canister. Obviously cost is a consideration, but reads and writes should be largely incremental, which means they're in a different (much smaller) ballpark.

**Comment by di-wu** [comment]
We'll see if it breaks in production.
