### ISSUE TITLE
Make reward badge assets

### ISSUE THREAD

**Issue by jorgenbuilder** [metascore/metascore#6]
See thoughts on reward badges here: https://github.com/metascore/metascore/blob/main/technical.md#ranks

**Comment by jorgenbuilder** [comment]
Currently reaching out to some artists on fiverr with this copy.

```
Hey,

I'm looking to get some badges developed for my gamer ranking system,

Tier 1: Gamer (this is mask-00.jpg)
Tier 2: Strong Gamer (this is mask-01.jpg)
Tier 3: Elite Gamer
Tier 4: #3 Gamer
Tier 5: #2 Gamer
Tier 6: The Most Powerful Gamer

I've attached some concept sketches. After the third mask/badge, we essentially just add increasingly badass crowns for the #1, #2, and #3 ranked players.

Are you into it? How quickly could you turnaround the first badge if we wanted to do a demo?
```

![mask-00](https://user-images.githubusercontent.com/60938577/131907969-a2bd766b-2c19-42a6-93d8-55d8c4cfa021.jpg)
![mask-01](https://user-images.githubusercontent.com/60938577/131907973-6ac6636e-43b9-4416-804c-99c601a52ab3.jpg)
![mask-02](https://user-images.githubusercontent.com/60938577/131907974-be01b174-1444-4d90-853c-1641614dc693.jpg)

**Comment by jorgenbuilder** [comment]
![Masks](https://user-images.githubusercontent.com/60938577/132031625-b4f3adf0-7b57-4042-9ed0-a9b8e7f5fa65.jpg)

**Comment by di-wu** [comment]
Whoow! Love this! 💯

**Comment by jorgenbuilder** [comment]
Just sent the artist a message about including **material progress**. We'll go from a tribal painted wood aesthetic to a forged platinum with blue diamonds aesthetic.

**Comment by jorgenbuilder** [comment]
![Masks (2)](https://user-images.githubusercontent.com/60938577/133907318-3604f895-dad7-43ea-b159-29c5c84d04a5.jpg)
